apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
  namespace: python-app
spec:
  containers:
  - name: stress
    image: progrium/stress
    command: ["stress"]
    args: ["--cpu", "1", "--timeout", "300s"]
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
      requests:
        cpu: "250m"
        memory: "64Mi"
