apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  namespace: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: <YOUR_ECR_IMAGE_URI>
        imagePullPolicy: Always         # ✅ Add this line
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"