apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: python-app
spec:
  selector:
    app: hello-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
